/* Generated by Phoenix Tuner X */
package frc.robot.subsystems.LEDs;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.RGBWColor;
import edu.wpi.first.wpilibj2.command.Commands;
/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LEDs extends SubsystemBase {
    private final CANBus kCANBus = new CANBus("canivorea");
    private final CANdle m_candle = new CANdle(20, kCANBus);
    private int r = 200;
    private int g = 0;
    private int b = 0;
    private int w = 0;
   private RGBWColor RGBWColor = new RGBWColor( r,  g,  b);


    private final SolidColor[] m_colors; 
        
            public LEDs() {
                //setDefaultCommand(updateLEDs());
               m_colors = new SolidColor[] {
        new SolidColor(0, 30).withColor(RGBWColor)
            };
            }
        
public void solidColorrgb() {
     {
            for (var solidColor : m_colors) {
                m_candle.setControl(solidColor);
            }}
}
        
            /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return Commands.run(() -> {
            for (var solidColor : m_colors) {
                m_candle.setControl(solidColor);
            }
        });
    }
}
