/* Generated by Phoenix Tuner X */
package frc.robot.subsystems.LEDs;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.RGBWColor;
import edu.wpi.first.wpilibj2.command.Commands;
/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LEDs extends SubsystemBase {
    private final CANBus kCANBus = new CANBus("canivorea");
    private final CANdle m_candle = new CANdle(20, kCANBus);
    private int r = 68;
    private int g = 47;
    private int b = 118;
   private RGBWColor EnableColor = new RGBWColor( r,  g,  b);
    private RGBWColor disableColor = new RGBWColor( 50,  40,  4);
   


    private final SolidColor[] m_colors; 
        
            public LEDs() {
                //setDefaultCommand(updateLEDs());
               m_colors = new SolidColor[] {
        new SolidColor(0, 30).withColor(EnableColor) ,
        new SolidColor(0, 30).withColor(disableColor)
            };
            }
        
public void solidColorrgb() {
        
                m_candle.setControl(m_colors[0]);
            
}
        
 @Override
 public void periodic() {

    if (DriverStation.isEnabled()) {
         m_candle.setControl(m_colors[0]);
    }
    else {
        m_candle.setControl(m_colors[1]);
    }
    
 }   











/**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return Commands.run(() -> {
            for (var solidColor : m_colors) {
                m_candle.setControl(solidColor);
            }
        });
    }
}
